"""initial schema

Revision ID: 953907ed750d
Revises:
Create Date: 2026-07-18 20:02:00.244836

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "953907ed750d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("code", sa.CHAR(length=2), nullable=False),
        sa.Column("name_ru", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_countries")),
    )
    op.create_table(
        "currencies",
        sa.Column("code", sa.CHAR(length=3), nullable=False),
        sa.Column("symbol", sa.String(length=4), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_currencies")),
    )
    op.create_table(
        "organizers",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column(
            "links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizers")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizers_slug")),
    )
    op.create_table(
        "otp_codes",
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= 5", name=op.f("ck_otp_codes_attempts_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_codes")),
    )
    op.create_index(
        "ix_otp_codes_phone_created_at", "otp_codes", ["phone", "created_at"], unique=False
    )
    op.create_table(
        "fx_rates",
        sa.Column("currency_code", sa.CHAR(length=3), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("rate_rub", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            name=op.f("fk_fx_rates_currency_code_currencies"),
        ),
        sa.PrimaryKeyConstraint("currency_code", "rate_date", name=op.f("pk_fx_rates")),
    )
    op.create_table(
        "users",
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("nickname", sa.String(length=32), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "base_currency", sa.CHAR(length=3), server_default=sa.text("'RUB'"), nullable=False
        ),
        sa.Column(
            "results_visibility",
            sa.Enum("private", "itm_only", "full", name="results_visibility"),
            server_default=sa.text("'private'"),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("user", "editor", "admin", name="user_role"),
            server_default=sa.text("'user'"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_currency"], ["currencies.code"], name=op.f("fk_users_base_currency_currencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("nickname", name=op.f("uq_users_nickname")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_table(
        "venues",
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("zone", sa.String(length=64), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"], ["countries.code"], name=op.f("fk_venues_country_code_countries")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venues")),
    )
    op.create_table(
        "bookmarks",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "target_type", sa.Enum("series", "flight", name="bookmark_target"), nullable=False
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reminder_offsets",
            postgresql.ARRAY(sa.Integer()),
            server_default=sa.text("'{1440,120}'::integer[]"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bookmarks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmarks")),
        sa.UniqueConstraint(
            "user_id", "target_type", "target_id", name="uq_bookmarks_user_id_target_type_target_id"
        ),
    )
    op.create_index(
        "ix_bookmarks_target_type_target_id",
        "bookmarks",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_table(
        "change_log",
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "change_type",
            sa.Enum("created", "updated", "cancelled", "schedule_published", name="change_type"),
            nullable=False,
        ),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "entity_type IN ('series', 'event', 'flight')",
            name=op.f("ck_change_log_entity_type_values"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_change_log_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_log")),
    )
    op.create_index(
        "ix_change_log_entity_type_entity_id_created_at",
        "change_log",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notification_queue",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "reminder",
                "schedule_published",
                "time_changed",
                "event_cancelled",
                "guarantee_changed",
                "series_starting",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="notification_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= 3", name=op.f("ck_notification_queue_attempts_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_queue_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_queue")),
    )
    op.create_index(
        "ix_notification_queue_status_scheduled_at",
        "notification_queue",
        ["status", "scheduled_at"],
        unique=False,
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column("device_label", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_push_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscriptions")),
        sa.UniqueConstraint("endpoint", name=op.f("uq_push_subscriptions_endpoint")),
    )
    op.create_table(
        "series",
        sa.Column("organizer_id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "announced",
                "schedule_published",
                "running",
                "finished",
                "cancelled",
                name="series_status",
            ),
            server_default=sa.text("'announced'"),
            nullable=False,
        ),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column(
            "links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organizer_id"], ["organizers.id"], name=op.f("fk_series_organizer_id_organizers")
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"], ["venues.id"], name=op.f("fk_series_venue_id_venues")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_series")),
    )
    op.create_index("ix_series_status_starts_on", "series", ["status", "starts_on"], unique=False)
    op.create_index("ix_series_venue_id", "series", ["venue_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "events",
        sa.Column("series_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("buyin", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency_code", sa.CHAR(length=3), nullable=False),
        sa.Column("guarantee", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "game_type",
            sa.Enum("nlh", "plo", "plo5", "mixed", "other", name="game_type"),
            server_default=sa.text("'nlh'"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("start_stack", sa.Integer(), nullable=True),
        sa.Column("reentry_count", sa.SmallInteger(), nullable=True),
        sa.Column(
            "reentry_unlimited", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("late_reg_level", sa.SmallInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("scheduled", "changed", "cancelled", name="event_status"),
            server_default=sa.text("'scheduled'"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"], ["currencies.code"], name=op.f("fk_events_currency_code_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
            name=op.f("fk_events_series_id_series"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index("ix_events_series_id_number", "events", ["series_id", "number"], unique=False)
    op.create_table(
        "import_jobs",
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("detected_type", sa.String(length=8), nullable=False),
        sa.Column("organizer_id", sa.UUID(), nullable=True),
        sa.Column("series_id", sa.UUID(), nullable=True),
        sa.Column("parser_used", sa.String(length=64), nullable=True),
        sa.Column("parse_path", sa.Enum("code", "ai", "mixed", name="parse_path"), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("tokens_input", sa.Integer(), nullable=True),
        sa.Column("tokens_output", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("uploaded", "parsing", "review", "published", "failed", name="import_status"),
            server_default=sa.text("'uploaded'"),
            nullable=False,
        ),
        sa.Column("draft", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "detected_type IN ('xlsx', 'csv', 'pdf', 'image')",
            name=op.f("ck_import_jobs_detected_type_values"),
        ),
        sa.ForeignKeyConstraint(
            ["organizer_id"], ["organizers.id"], name=op.f("fk_import_jobs_organizer_id_organizers")
        ),
        sa.ForeignKeyConstraint(
            ["series_id"], ["series.id"], name=op.f("fk_import_jobs_series_id_series")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_import_jobs_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
    )
    op.create_table(
        "blind_levels",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("level_no", sa.SmallInteger(), nullable=False),
        sa.Column("sb", sa.Integer(), nullable=True),
        sa.Column("bb", sa.Integer(), nullable=True),
        sa.Column("ante", sa.Integer(), nullable=True),
        sa.Column("minutes", sa.SmallInteger(), nullable=False),
        sa.Column("is_break", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_late_reg_end", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_blind_levels_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blind_levels")),
        sa.UniqueConstraint("event_id", "level_no", name="uq_blind_levels_event_id_level_no"),
    )
    op.create_table(
        "flights",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_flights_event_id_events"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flights")),
    )
    op.create_index("ix_flights_event_id", "flights", ["event_id"], unique=False)
    op.create_index("ix_flights_start_at", "flights", ["start_at"], unique=False)
    op.create_table(
        "results",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum("live_mtt", name="entry_type"),
            server_default=sa.text("'live_mtt'"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("venue_text", sa.String(length=160), nullable=True),
        sa.Column("series_text", sa.String(length=160), nullable=True),
        sa.Column("played_on", sa.Date(), nullable=False),
        sa.Column("buyin", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency_code", sa.CHAR(length=3), nullable=False),
        sa.Column("entries_count", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "payout", sa.Numeric(precision=14, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("place", sa.Integer(), nullable=True),
        sa.Column("field_size", sa.Integer(), nullable=True),
        sa.Column(
            "my_share_pct",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("100"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"], ["currencies.code"], name=op.f("fk_results_currency_code_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_results_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_results_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_results")),
    )
    op.create_index(
        "ix_results_user_id_played_on", "results", ["user_id", "played_on"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_results_user_id_played_on", table_name="results")
    op.drop_table("results")
    op.drop_index("ix_flights_start_at", table_name="flights")
    op.drop_index("ix_flights_event_id", table_name="flights")
    op.drop_table("flights")
    op.drop_table("blind_levels")
    op.drop_table("import_jobs")
    op.drop_index("ix_events_series_id_number", table_name="events")
    op.drop_table("events")
    op.drop_table("sessions")
    op.drop_index("ix_series_venue_id", table_name="series")
    op.drop_index("ix_series_status_starts_on", table_name="series")
    op.drop_table("series")
    op.drop_table("push_subscriptions")
    op.drop_index("ix_notification_queue_status_scheduled_at", table_name="notification_queue")
    op.drop_table("notification_queue")
    op.drop_index("ix_change_log_entity_type_entity_id_created_at", table_name="change_log")
    op.drop_table("change_log")
    op.drop_index("ix_bookmarks_target_type_target_id", table_name="bookmarks")
    op.drop_table("bookmarks")
    op.drop_table("venues")
    op.drop_table("users")
    op.drop_table("fx_rates")
    op.drop_index("ix_otp_codes_phone_created_at", table_name="otp_codes")
    op.drop_table("otp_codes")
    op.drop_table("organizers")
    op.drop_table("currencies")
    op.drop_table("countries")
    for enum_name in (
        "parse_path",
        "import_status",
        "entry_type",
        "event_status",
        "game_type",
        "series_status",
        "notification_status",
        "notification_type",
        "change_type",
        "bookmark_target",
        "user_role",
        "results_visibility",
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
